import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        background: "#fcf9f8",
        surface: "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#4c4355",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        outline: "#7d7387",
        "outline-variant": "#cec2d8",
        "surface-tint": "#8018ea",
        primary: "#6f00d2",
        "on-primary": "#ffffff",
        "primary-container": "#8b2cf5",
        "on-primary-container": "#f2e3ff",
        "inverse-primary": "#d8b9ff",
        secondary: "#2000c7",
        "on-secondary": "#ffffff",
        "secondary-container": "#3217ff",
        "on-secondary-container": "#c1c0ff",
        tertiary: "#6a4b00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#886200",
        "on-tertiary-container": "#ffe6bc",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#eddcff",
        "primary-fixed-dim": "#d8b9ff",
        "on-primary-fixed": "#290055",
        "on-primary-fixed-variant": "#6300bb",
        "secondary-fixed": "#e2dfff",
        "secondary-fixed-dim": "#c2c1ff",
        "on-secondary-fixed": "#0c006a",
        "on-secondary-fixed-variant": "#2700e8",
        "tertiary-fixed": "#ffdea6",
        "tertiary-fixed-dim": "#f3be56",
        "on-tertiary-fixed": "#271900",
        "on-tertiary-fixed-variant": "#5d4200",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        lg: "40px",
        xs: "4px",
        md: "24px",
        sm: "12px",
        xl: "64px",
        base: "8px",
        "container-margin": "20px",
      },
      fontFamily: {
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-bold": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
      },
      boxShadow: {
        card: "0 4px 20px rgba(139, 44, 245, 0.04)",
        floating: "0 8px 16px rgba(111, 0, 210, 0.2)",
        "floating-hover": "0 12px 24px rgba(111, 0, 210, 0.3)",
      },
    },
  },
  plugins: [],
};

export default config;
